FROM       docker-dev.ops.tune.com/itops/base_centos6:latest
MAINTAINER Yoon Soo Pyon yoon@tune.com

# install test
RUN yum -y install tar wget which

# run test
ENTRYPOINT ["echo"]
CMD ["tests should be run here"]
